"""Optional official-code parity with synthetic, freely generated HDF5 matrices.

No atlas or biological label is generated by these tests.
"""
import json
from pathlib import Path
import numpy as np
import pandas as pd
import pytest

pytest.importorskip('phosx')
import h5py
from phosx.utils import AA_LIST,POSITIONS_LIST,read_pssms,read_pssm_score_quantiles
from phosx.pssms import pssm_scoring,quantile_scaling,binarise_pssm_scores
from ptm_shared.annotation_registry import digest
from ptm_shared.official_specificity import score_phosx
from ptm_shared.tests.test_astra_science import config


@pytest.fixture
def resource(tmp_path):
    matrix=tmp_path/'matrix.h5';background=tmp_path/'background.h5'
    with h5py.File(matrix,'w') as f:
        for n in range(7):
            weights=np.ones((len(POSITIONS_LIST),len(AA_LIST)))
            weights[0,:]=1.8-n*.21
            f.create_dataset('K'+str(n),data=weights)
    pd.DataFrame({f'K{n}':np.linspace(.1,2.,1001) for n in range(7)}).to_hdf(background,key='pssm_scores')
    meta={'adapter':'phosx_official.v1','resource_id':'synthetic_test_only','resource_version':'1',
        'publication_doi':None,'source_url':'synthetic_fixture','license_identifier':'CC0-1.0',
        'local_use_permission':'permitted','derived_export_permission':'permitted','redistribution_status':'permitted',
        'assay_taxon':'9606','supported_center_residues':['S','T'],'matrix_file':matrix.name,'background_file':background.name,
        'matrix_sha256':digest(matrix),'background_sha256':digest(background),'n_top_kinases':5,'min_quantile':.8,
        'enzyme_mapping':{f'K{n}':{'accession':f'K{n}','taxon':'9606'} for n in range(7)}}
    path=tmp_path/'specificity.json';path.write_text(json.dumps(meta));return path


def test_official_score_percentile_and_membership_parity(resource):
    from ptm_shared.kinase_specificity import score_sites
    sites=pd.DataFrame([{'site_id':'s','form_id':'f','measurement_group_id':'m','input_accession':'P',
        'input_position':6,'substrate_taxon':'10090','form_modification_count':1}])
    entries=[{'accession':'P','sequence':'AAAAASAAAA'}]
    actual,status=score_sites(sites,entries,resource,official=True)
    matrices=read_pssms(str(resource.parent/'matrix.h5'));bg=read_pssm_score_quantiles(str(resource.parent/'background.h5'))
    raw=pssm_scoring('AAAAASAAAA',matrices)
    reference=pd.DataFrame([raw]).apply(quantile_scaling,args=[{k:np.sort(bg[k]) for k in bg}],axis=0)
    membership=binarise_pssm_scores(reference,n=5,m=.8)
    for r in actual.itertuples():
        assert r.score==pytest.approx(raw[r.kinase_accession],rel=1e-12,abs=1e-12)
        assert r.percentile==pytest.approx(reference[r.kinase_accession].iloc[0]*100,rel=1e-12,abs=1e-12)
        assert r.membership_selected==membership[r.kinase_accession].iloc[0]
        assert r.substrate_taxon=='10090' and r.kinase_taxon=='9606'
    assert actual.membership_selected.any() and not actual.membership_selected.all()
    assert status['official_full_method_executed'] is False


@pytest.mark.parametrize('redistribution',['permitted','prohibited'])
def test_native_method_reaches_package_and_offline_replay(config,resource,tmp_path,redistribution):
    from ptm_shared.astra_evidence_v6 import run
    from ptm_shared.astra_package import replay_package
    # Use official fixed activity thresholds; resource's custom PSSM preview
    # settings do not silently alter the official activity method.
    meta=json.loads(resource.read_text());meta['min_quantile']=.95;meta['redistribution_status']=redistribution
    resource.write_text(json.dumps(meta))
    config['specificity_manifest_path']=str(resource)
    context=config['experimental_context'];context['quantitation_export_mode']='astra_analysis.v6'
    context['science']['official_methods']={'PhosX':{'permutations':100,'seed':1729}}
    result=run(1,config,tmp_path/'out');root=tmp_path/'out/enrichment_free_runs'/result['run_id']
    executions=pd.read_csv(root/'kinase/method_executions.csv')
    assert len(executions) and executions.status.eq('executed').all()
    assert len(pd.read_csv(root/'kinase/method_membership.csv'))
    assert pd.read_csv(root/'kinase/method_scores.csv').method_id.eq('PhosX_native_functions').any()
    if redistribution=='prohibited':
        assert not list((root/'inputs').rglob('*.h5'))
        with pytest.raises(ValueError,match='Conditional replay'):replay_package(root,tmp_path/'missing_resource')
        replay_package(root,tmp_path/'replay',specificity_manifest=resource)
    else:replay_package(root,tmp_path/'replay')
