"""
PPTX generation (sync) — used by Celery worker. Mirrors api-server presentation logic.
"""

from __future__ import annotations

import json
import logging
import os
from collections.abc import Callable
from pathlib import Path
from typing import Any

from sqlalchemy import text

from common.db_engine import get_engine

logger = logging.getLogger("ptm-workers.pptx")

def _render_pptx(slide_data: dict, output_path: str, figure_dir: Path, *, approved_figures=None) -> str:
    from pptx import Presentation
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    def _safe_str(x, default="") -> str:
        if x is None:
            return default
        s = str(x).strip()
        return s if s else default

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    DARK_BG = RGBColor(0x1A, 0x1A, 0x2E)
    ACCENT = RGBColor(0x64, 0xB5, 0xF6)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    LIGHT_GRAY = RGBColor(0xCC, 0xCC, 0xCC)
    DARK_TEXT = RGBColor(0x33, 0x33, 0x33)
    SECTION_BG = RGBColor(0x0D, 0x47, 0xA1)

    figure_map = dict(approved_figures or {})

    def _add_bg(slide, color):
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = color

    def _add_text_box(slide, left, top, width, height, text, font_size=18,
                      color=WHITE, bold=False, alignment=PP_ALIGN.LEFT):
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(font_size)
        p.font.color.rgb = color
        p.font.bold = bold
        p.alignment = alignment
        return txBox

    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, DARK_BG)
    _add_text_box(slide, 1.5, 2.0, 10.3, 1.5,
                  _safe_str(slide_data.get("title"), "PTM Analysis Report"),
                  font_size=36, color=WHITE, bold=True, alignment=PP_ALIGN.LEFT)
    _add_text_box(slide, 1.5, 3.8, 10.3, 1.0,
                  _safe_str(slide_data.get("subtitle")),
                  font_size=20, color=LIGHT_GRAY, alignment=PP_ALIGN.LEFT)
    _add_text_box(slide, 1.5, 5.8, 10.3, 0.6,
                  "Generated by MEKII AI  |  PTM Analysis Platform",
                  font_size=14, color=ACCENT, alignment=PP_ALIGN.LEFT)

    slides_data = slide_data.get("slides", [])
    if not isinstance(slides_data, list):
        slides_data = []
    for i, sd in enumerate(slides_data):
        if not isinstance(sd, dict):
            continue
        layout = _safe_str(sd.get("layout"), "content")
        title = _safe_str(sd.get("title"), f"Slide {i + 2}")
        raw_bullets = sd.get("bullets") or []
        if not isinstance(raw_bullets, list):
            raw_bullets = [raw_bullets] if raw_bullets else []
        bullets = [_safe_str(b) for b in raw_bullets if _safe_str(b)]
        notes = _safe_str(sd.get("notes"))
        suggest_fig = _safe_str(sd.get("suggest_figure"), "none").lower().replace(" ", "_")

        if layout == "section_header":
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide, SECTION_BG)
            _add_text_box(slide, 1.5, 2.5, 10.3, 2.0, title,
                          font_size=32, color=WHITE, bold=True, alignment=PP_ALIGN.LEFT)
            if bullets:
                _add_text_box(slide, 1.5, 4.5, 10.3, 1.5, bullets[0],
                              font_size=18, color=LIGHT_GRAY, alignment=PP_ALIGN.LEFT)
        else:
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide, RGBColor(0xF8, 0xF9, 0xFA))
            title_shape = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), prs.slide_width, Inches(1.1)
            )
            title_shape.fill.solid()
            title_shape.fill.fore_color.rgb = DARK_BG
            title_shape.line.fill.background()
            _add_text_box(slide, 0.8, 0.15, 11.7, 0.8, title,
                          font_size=26, color=WHITE, bold=True)
            has_figure = suggest_fig != "none" and suggest_fig in figure_map
            content_width = 6.5 if has_figure else 11.0
            if bullets:
                txBox = slide.shapes.add_textbox(
                    Inches(0.8), Inches(1.5), Inches(content_width), Inches(5.2)
                )
                tf = txBox.text_frame
                tf.word_wrap = True
                for j, bullet in enumerate(bullets):
                    p = tf.paragraphs[0] if j == 0 else tf.add_paragraph()
                    p.text = f"•  {bullet}"
                    p.font.size = Pt(16)
                    p.font.color.rgb = DARK_TEXT
                    p.space_after = Pt(10)
            if has_figure:
                fig_path = figure_map[suggest_fig]
                try:
                    slide.shapes.add_picture(
                        str(fig_path), Inches(7.8), Inches(1.5), Inches(4.8), Inches(5.0)
                    )
                except Exception as e:
                    raise ValueError("approved_figure_render_failed") from e
        if notes:
            slide.notes_slide.notes_text_frame.text = notes

    prs.save(output_path)
    return output_path


def _extract_balanced_json_object(text: str) -> str | None:
    """Find the first `{` and return the substring through its matching `}` (string-aware)."""
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(text)):
        c = text[i]
        if in_string:
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_string = False
            continue
        if c == '"':
            in_string = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _parse_json(raw: str) -> dict | None:
    text = raw.strip()
    # ```json ... ``` — fenced blocks often contain valid JSON even with preamble outside
    if "```" in text:
        for block in text.split("```"):
            b = block.strip()
            if not b or "{" not in b:
                continue
            if b.lower().startswith("json"):
                b = b[4:].lstrip()
            blob = _extract_balanced_json_object(b)
            if blob:
                try:
                    return json.loads(blob)
                except json.JSONDecodeError:
                    continue
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    blob = _extract_balanced_json_object(text)
    if blob:
        try:
            return json.loads(blob)
        except json.JSONDecodeError:
            pass
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            return None
    return None


def _parse_json_context(val: Any) -> dict:
    if val is None:
        return {}
    if isinstance(val, dict):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except json.JSONDecodeError:
            return {}
    return {}


def slide_plan_from_revision(plan, packet, revision):
    """Use approved observations verbatim; the slide model cannot invent raw FC rankings."""
    import re
    cards = {c.get('card_id'): c for c in packet.get('reader_cards') or []}
    all_evidence = {e for c in cards.values() for e in c.get('evidence_ids') or []}
    slides = []
    for finding in plan.get('key_findings') or []:
        if not set(finding.get('evidence_ids') or []).issubset(all_evidence):
            raise ValueError('slide_finding_evidence_unbound')
        observation = str(finding.get('observation') or '')
        observation = re.sub(r'\[(?:EVID|REF):[^]]+\]', '', observation).strip()
        limitation = str(finding.get('alternative_explanation') or '')
        # No free-text scientific rewriting. Longer observations continue over
        # multiple slides instead of silently losing trailing qualifications.
        import textwrap
        segments = textwrap.wrap(observation, width=600, break_long_words=False, break_on_hyphens=False) or ['']
        for index, segment in enumerate(segments):
            slides.append({'title': finding.get('reader_display_identity') or 'Observed pattern',
                           'layout': 'content', 'bullets': [segment, limitation],
                           'claim_ids': [finding.get('finding_id')], 'evidence_ids': finding.get('evidence_ids', []),
                           'reference_ids': finding.get('citation_ids', []), 'required_limitations': [limitation],
                           'suggest_figure': next(iter(finding.get('figure_keys') or []), 'none'),
                           'notes': json.dumps({'source_revision_id': revision['revision_id'],
                                                'references': revision.get('references', []),
                                                'next_test_hypothesis': finding.get('next_test'),
                                                'continuation': index}, ensure_ascii=False)})
    if not slides:
        raise ValueError('no_approved_findings_for_presentation')
    return {'schema_version': 'revision_slide_plan.v1', 'source_revision_id': revision['revision_id'],
            'title': 'PTM Analysis Report — Review draft',
            'subtitle': 'Slide layout review pending. ' + str(plan.get('central_question', '')),
            'slides': slides, 'omitted_findings': plan.get('finding_selection_audit', {}).get('exclusions', [])}


def generate_pptx_for_order_sync(
    order_id: int,
    llm_provider: str,
    llm_model: str,
    *,
    on_progress: Callable[[str, str, int], None] | None = None,
    source_revision_id: str | None = None,
) -> dict[str, Any]:
    """
    Build PPTX for order. Returns dict with filename, slide_count, figures_embedded.
    Raises RuntimeError on failure.
    """
    engine = get_engine()
    with engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT order_code, ptm_type, analysis_context, report_options FROM orders WHERE id = :oid"
            ),
            {"oid": order_id},
        ).mappings().first()
    if not row:
        raise RuntimeError("Order not found")

    order_code = row["order_code"] or str(order_id)
    ptm_type = row["ptm_type"] or "phosphorylation"
    ctx = _parse_json_context(row["analysis_context"])
    report_opts = _parse_json_context(row["report_options"])

    output_dir = Path(os.getenv("OUTPUT_DIR", "/app/data/outputs")) / order_code
    if not output_dir.exists():
        raise RuntimeError("No analysis output directory for this order")

    from ptm_shared.report_revision import read_revision, verify_revision, revision_packet, register_revision
    if not source_revision_id:
        raise RuntimeError("Pinned source revision is required; legacy jobs must be resubmitted")
    revision = read_revision(output_dir, source_revision_id)
    if not revision or revision['release'].get('publish_as_final') is not True:
        raise RuntimeError('source_revision_not_final_ready')
    verify_revision(output_dir, revision)
    plan = revision_packet(output_dir, revision, 'reader_authoring_plan')
    packet = revision_packet(output_dir, revision, 'authoring_packet')
    parsed = slide_plan_from_revision(plan, packet, revision)
    figures = {a['role'].split(':', 1)[1]: output_dir / a['filename']
               for a in revision['artifacts'] if a['role'].startswith('figure:')}

    pptx_name = f"{order_code}_{source_revision_id}_presentation.pptx"
    pptx_path = str(output_dir / pptx_name)
    if on_progress:
        on_progress("render", "Building PPTX file and embedding figures…", 70)
    _render_pptx(parsed, pptx_path, output_dir, approved_figures=figures)
    from report_generation.core.report_artifact_manifest import _artifact, finalize_rendered_artifacts
    from report_generation.core.report_release import resolve_report_release
    from ptm_shared.report_revision import _atomic_json
    slide_plan_path = output_dir / (f"{source_revision_id}_slide_plan.json")
    _atomic_json(slide_plan_path, parsed)
    manifest = finalize_rendered_artifacts({"status": "validated", "report_eligible": True,
        "artifacts": [_artifact('slide_plan', slide_plan_path, required=True)]},
        [pptx_path], {}, requested_formats=['pptx'])
    # A parent's final status cannot certify a newly rendered slide layout.
    release = resolve_report_release(reader_authoring_shadow=True,
        output_correctness={"status": "draft_review_required", "reason_codes": ["presentation_visual_review_pending"]},
        artifact_manifest=manifest,
        report_mode_contract=revision.get('manifest', {}).get('report_mode_contract'))
    derived = register_revision(output_dir, files=[pptx_path], manifest=manifest,
                                release=release, references=revision["references"],
                                source_revisions=[{"revision_id": source_revision_id, "registry_sha256": revision["registry_sha256"]}], make_current=False)
    pptx_name = next(a["filename"] for a in derived["artifacts"] if a["role"] == "report")
    if on_progress:
        on_progress("finalize", "Saving presentation…", 92)

    return {
        "status": "ok",
        "filename": pptx_name,
        "source_revision_id": source_revision_id,
        "revision_id": derived["revision_id"],
        "slide_count": len(parsed.get("slides", [])) + 1,
        "figures_embedded": [k for k in figures if k in str(parsed)],
    }
