"""
PPTX generation (sync) — used by Celery worker. Mirrors api-server presentation logic.
"""

from __future__ import annotations

import json
import logging
import os
from collections.abc import Callable
from pathlib import Path
from typing import Any

import httpx
from sqlalchemy import text

from common.db_engine import get_engine

logger = logging.getLogger("ptm-workers.pptx")

MAX_REPORT_CHARS = 12000
MAX_DATA_CHARS = 4000

SYSTEM_PROMPT = """\
You are a scientific presentation designer. Given a PTM (post-translational modification)
analysis report and data summaries, create a structured slide deck for a research presentation.

CRITICAL: Your entire reply must be ONLY one JSON object — no markdown headings (no ## lines),
no "Instructions", no preamble, no code fences, no text before `{` or after the closing `}`.

## RULES
1. Create 8-12 slides covering the key findings
2. Each slide should have a clear title, 3-5 bullet points, and optional speaker notes
3. Include slides for: Title, Background/Objective, Methods, Key Findings (2-3 slides),
   Signaling Architecture, Temporal Dynamics, Discussion, Conclusions, Future Directions
4. Use actual protein names, PTM sites, and data values from the report
5. Keep bullets concise (max 15 words each)
6. Speaker notes should provide additional context for the presenter (2-3 sentences)
7. If figures are available, reference them by suggesting which slide should include them

## OUTPUT FORMAT
Return ONLY a valid JSON object (no markdown fences, no commentary):
{
  "title": "Presentation title",
  "subtitle": "Subtitle or experiment description",
  "slides": [
    {
      "title": "Slide Title",
      "layout": "title | content | two_column | section_header",
      "bullets": ["Point 1", "Point 2", "Point 3"],
      "notes": "Speaker notes for this slide",
      "suggest_figure": "signal_flow | comovement | cascade | network | none"
    }
  ]
}
"""

USER_PROMPT_TEMPLATE = """\
## Experiment Overview
- Order: {order_code}
- PTM Type: {ptm_type}
- Treatment: {treatment}
- Time Points: {time_points}
- Species: {species}

## Research Questions
{research_questions}

## Report Content (Summary)
{report_summary}

## Key Data Points
{data_summary}

## Available Figures
{figure_list}

## Task
Create a structured presentation (8-12 slides) covering the most important
findings from this PTM analysis. Focus on biological significance and
actionable insights.
"""


def _render_pptx(slide_data: dict, output_path: str, figure_dir: Path) -> str:
    from pptx import Presentation
    from pptx.enum.shapes import MSO_SHAPE
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    def _safe_str(x, default="") -> str:
        if x is None:
            return default
        s = str(x).strip()
        return s if s else default

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    DARK_BG = RGBColor(0x1A, 0x1A, 0x2E)
    ACCENT = RGBColor(0x64, 0xB5, 0xF6)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    LIGHT_GRAY = RGBColor(0xCC, 0xCC, 0xCC)
    DARK_TEXT = RGBColor(0x33, 0x33, 0x33)
    SECTION_BG = RGBColor(0x0D, 0x47, 0xA1)

    figure_map = _collect_figures(figure_dir)

    def _add_bg(slide, color):
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = color

    def _add_text_box(slide, left, top, width, height, text, font_size=18,
                      color=WHITE, bold=False, alignment=PP_ALIGN.LEFT):
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(font_size)
        p.font.color.rgb = color
        p.font.bold = bold
        p.alignment = alignment
        return txBox

    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, DARK_BG)
    _add_text_box(slide, 1.5, 2.0, 10.3, 1.5,
                  _safe_str(slide_data.get("title"), "PTM Analysis Report"),
                  font_size=36, color=WHITE, bold=True, alignment=PP_ALIGN.LEFT)
    _add_text_box(slide, 1.5, 3.8, 10.3, 1.0,
                  _safe_str(slide_data.get("subtitle")),
                  font_size=20, color=LIGHT_GRAY, alignment=PP_ALIGN.LEFT)
    _add_text_box(slide, 1.5, 5.8, 10.3, 0.6,
                  "Generated by POTATO AI  |  PTM Analysis Platform",
                  font_size=14, color=ACCENT, alignment=PP_ALIGN.LEFT)

    slides_data = slide_data.get("slides", [])
    if not isinstance(slides_data, list):
        slides_data = []
    for i, sd in enumerate(slides_data):
        if not isinstance(sd, dict):
            continue
        layout = _safe_str(sd.get("layout"), "content")
        title = _safe_str(sd.get("title"), f"Slide {i + 2}")
        raw_bullets = sd.get("bullets") or []
        if not isinstance(raw_bullets, list):
            raw_bullets = [raw_bullets] if raw_bullets else []
        bullets = [_safe_str(b) for b in raw_bullets if _safe_str(b)]
        notes = _safe_str(sd.get("notes"))
        suggest_fig = _safe_str(sd.get("suggest_figure"), "none").lower().replace(" ", "_")

        if layout == "section_header":
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide, SECTION_BG)
            _add_text_box(slide, 1.5, 2.5, 10.3, 2.0, title,
                          font_size=32, color=WHITE, bold=True, alignment=PP_ALIGN.LEFT)
            if bullets:
                _add_text_box(slide, 1.5, 4.5, 10.3, 1.5, bullets[0],
                              font_size=18, color=LIGHT_GRAY, alignment=PP_ALIGN.LEFT)
        else:
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide, RGBColor(0xF8, 0xF9, 0xFA))
            title_shape = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), prs.slide_width, Inches(1.1)
            )
            title_shape.fill.solid()
            title_shape.fill.fore_color.rgb = DARK_BG
            title_shape.line.fill.background()
            _add_text_box(slide, 0.8, 0.15, 11.7, 0.8, title,
                          font_size=26, color=WHITE, bold=True)
            has_figure = suggest_fig != "none" and suggest_fig in figure_map
            content_width = 6.5 if has_figure else 11.0
            if bullets:
                txBox = slide.shapes.add_textbox(
                    Inches(0.8), Inches(1.5), Inches(content_width), Inches(5.2)
                )
                tf = txBox.text_frame
                tf.word_wrap = True
                for j, bullet in enumerate(bullets):
                    p = tf.paragraphs[0] if j == 0 else tf.add_paragraph()
                    p.text = f"•  {bullet}"
                    p.font.size = Pt(16)
                    p.font.color.rgb = DARK_TEXT
                    p.space_after = Pt(10)
            if has_figure:
                fig_path = figure_map[suggest_fig]
                try:
                    slide.shapes.add_picture(
                        str(fig_path), Inches(7.8), Inches(1.5), Inches(4.8), Inches(5.0)
                    )
                except Exception as e:
                    logger.warning("Failed to embed figure %s: %s", fig_path, e)
        if notes:
            slide.notes_slide.notes_text_frame.text = notes

    prs.save(output_path)
    return output_path


def _collect_figures(output_dir: Path) -> dict[str, Path]:
    mapping: dict[str, Path] = {}
    if not output_dir.exists():
        return mapping
    for p in output_dir.glob("*.png"):
        name = p.stem.lower()
        if "signal_flow" in name:
            mapping.setdefault("signal_flow", p)
        elif "comovement" in name or "co_movement" in name:
            mapping.setdefault("comovement", p)
        elif "cascade" in name or "signaling_cascade" in name:
            mapping.setdefault("cascade", p)
        elif "network" in name or "cytoscape" in name:
            mapping.setdefault("network", p)
        elif "heatmap" in name:
            mapping.setdefault("heatmap", p)
    return mapping


def _load_report_text(output_dir: Path, file_suffix: str) -> str:
    candidates = sorted(
        output_dir.glob("*_report_*.md"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if candidates:
        text = candidates[0].read_text(encoding="utf-8", errors="replace")
        return text[:MAX_REPORT_CHARS]
    for name in (f"comprehensive_report{file_suffix}.md", "final_report.md", "report.md"):
        alt = output_dir / name
        if alt.exists():
            return alt.read_text(encoding="utf-8", errors="replace")[:MAX_REPORT_CHARS]
    return ""


def _load_data_summary(output_dir: Path, file_suffix: str) -> str:
    json_path = None
    for p in sorted(output_dir.glob(f"enriched_ptm_data{file_suffix}*.json"), reverse=True):
        json_path = p
        break
    if not json_path:
        for p in sorted(output_dir.glob("enriched_ptm_data*.json"), reverse=True):
            json_path = p
            break
    if not json_path:
        return "(No enriched data available)"
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
    except Exception:
        return "(Failed to load data)"
    lines = [f"Total PTMs: {len(data)}"]
    scored = []
    for p in data:
        gene = p.get("gene_name", p.get("Gene_Name", "?"))
        pos = p.get("position", p.get("Position", "?"))
        fc = p.get("fold_change", p.get("Fold_Change", 0))
        try:
            abs_fc = abs(float(fc))
        except (ValueError, TypeError):
            abs_fc = 0
        scored.append((abs_fc, gene, pos, fc))
    scored.sort(reverse=True)
    lines.append("\nTop 15 PTMs by |fold-change|:")
    for abs_fc, gene, pos, fc in scored[:15]:
        lines.append(f"  {gene}-{pos}: FC={fc}")
    return "\n".join(lines)[:MAX_DATA_CHARS]


def _extract_balanced_json_object(text: str) -> str | None:
    """Find the first `{` and return the substring through its matching `}` (string-aware)."""
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escape = False
    for i in range(start, len(text)):
        c = text[i]
        if in_string:
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_string = False
            continue
        if c == '"':
            in_string = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None


def _parse_json(raw: str) -> dict | None:
    text = raw.strip()
    # ```json ... ``` — fenced blocks often contain valid JSON even with preamble outside
    if "```" in text:
        for block in text.split("```"):
            b = block.strip()
            if not b or "{" not in b:
                continue
            if b.lower().startswith("json"):
                b = b[4:].lstrip()
            blob = _extract_balanced_json_object(b)
            if blob:
                try:
                    return json.loads(blob)
                except json.JSONDecodeError:
                    continue
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    blob = _extract_balanced_json_object(text)
    if blob:
        try:
            return json.loads(blob)
        except json.JSONDecodeError:
            pass
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            return None
    return None


def _call_llm_sync(provider: str, model: str, system_prompt: str, user_prompt: str) -> str:
    ollama_url = os.getenv("OLLAMA_URL", "http://host.docker.internal:11434")
    timeout = httpx.Timeout(600.0, connect=30.0)

    if provider not in ("gemini", "openai", "ollama"):
        raise RuntimeError(
            f"PPTX는 provider '{provider}'를 지원하지 않습니다. Ollama, Gemini, OpenAI 중에서 선택하세요."
        )

    with httpx.Client(timeout=timeout) as client:
        if provider == "gemini":
            api_key = os.getenv("GEMINI_API_KEY", "")
            if not api_key:
                raise RuntimeError("GEMINI_API_KEY not configured")
            model_id = model or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_id}:generateContent?key={api_key}"
            resp = client.post(url, json={
                "contents": [{"parts": [{"text": f"{system_prompt}\n\n{user_prompt}"}]}],
                "generationConfig": {"temperature": 0.4, "maxOutputTokens": 8192},
            })
            resp.raise_for_status()
            data = resp.json()
            cands = data.get("candidates") or []
            if not cands:
                raise RuntimeError(f"Gemini returned no candidates: {data!r:.800}")
            parts = (cands[0].get("content") or {}).get("parts") or []
            texts = [p.get("text", "") for p in parts if isinstance(p, dict)]
            out = "".join(texts).strip()
            if not out:
                raise RuntimeError("Gemini returned empty text.")
            return out

        if provider == "openai":
            api_key = os.getenv("OPENAI_API_KEY", "")
            if not api_key:
                raise RuntimeError("OPENAI_API_KEY not configured")
            model_id = model or os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
            resp = client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": model_id,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    "temperature": 0.4,
                    "max_tokens": 8192,
                    "response_format": {"type": "json_object"},
                },
            )
            resp.raise_for_status()
            data = resp.json()
            msg = (data.get("choices") or [{}])[0].get("message") or {}
            return (msg.get("content") or "").strip() or ""

        model_id = model or os.getenv("LLM_MODEL", "gemma3:27b")
        resp = client.post(
            f"{ollama_url}/api/chat",
            json={
                "model": model_id,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.4, "num_predict": 8192},
            },
        )
        resp.raise_for_status()
        body = resp.json()
        content = (body.get("message") or {}).get("content") or ""
        if not content.strip():
            raise RuntimeError(
                f"Ollama returned empty content for model '{model_id}'. Raw: {body!r:.500}"
            )
        return content


def _parse_json_context(val: Any) -> dict:
    if val is None:
        return {}
    if isinstance(val, dict):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except json.JSONDecodeError:
            return {}
    return {}


def generate_pptx_for_order_sync(
    order_id: int,
    llm_provider: str,
    llm_model: str,
    *,
    on_progress: Callable[[str, str, int], None] | None = None,
) -> dict[str, Any]:
    """
    Build PPTX for order. Returns dict with filename, slide_count, figures_embedded.
    Raises RuntimeError on failure.
    """
    engine = get_engine()
    with engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT order_code, ptm_type, analysis_context, report_options FROM orders WHERE id = :oid"
            ),
            {"oid": order_id},
        ).mappings().first()
    if not row:
        raise RuntimeError("Order not found")

    order_code = row["order_code"] or str(order_id)
    ptm_type = row["ptm_type"] or "phosphorylation"
    ctx = _parse_json_context(row["analysis_context"])
    report_opts = _parse_json_context(row["report_options"])

    output_dir = Path(os.getenv("OUTPUT_DIR", "/app/data/outputs")) / order_code
    if not output_dir.exists():
        raise RuntimeError("No analysis output directory for this order")

    file_suffix = "_phospho" if ptm_type == "phosphorylation" else "_ubi"
    report_text = _load_report_text(output_dir, file_suffix)
    if not report_text:
        raise RuntimeError("No report found. Run Report Generation first.")

    data_summary = _load_data_summary(output_dir, file_suffix)
    figures = _collect_figures(output_dir)
    figure_list = ", ".join(figures.keys()) if figures else "None"
    rqs = report_opts.get("research_questions") or []

    user_prompt = USER_PROMPT_TEMPLATE.format(
        order_code=order_code,
        ptm_type=ptm_type,
        treatment=ctx.get("treatment", "N/A"),
        time_points=ctx.get("time_points", ctx.get("timepoints", "N/A")),
        species=ctx.get("species", "N/A"),
        research_questions="\n".join(f"- {q}" for q in rqs) if rqs else "(None)",
        report_summary=report_text,
        data_summary=data_summary,
        figure_list=figure_list,
    )

    logger.info("[PPTX] order=%s provider=%s model=%s", order_code, llm_provider, llm_model)
    if on_progress:
        on_progress(
            "llm",
            "Generating slide structure with LLM (this may take several minutes)…",
            25,
        )
    raw = _call_llm_sync(llm_provider, llm_model, SYSTEM_PROMPT, user_prompt)

    parsed = _parse_json(raw)
    if not parsed or "slides" not in parsed:
        snippet = (raw or "")[:600].replace("\n", " ")
        raise RuntimeError(
            f"LLM 응답을 슬라이드 JSON으로 파싱하지 못했습니다. (응답 앞부분: {snippet!r})"
        )

    pptx_name = f"{order_code}_presentation.pptx"
    pptx_path = str(output_dir / pptx_name)
    if on_progress:
        on_progress("render", "Building PPTX file and embedding figures…", 70)
    _render_pptx(parsed, pptx_path, output_dir)
    if on_progress:
        on_progress("finalize", "Saving presentation…", 92)

    return {
        "status": "ok",
        "filename": pptx_name,
        "slide_count": len(parsed.get("slides", [])) + 1,
        "figures_embedded": [k for k in figures if k in str(parsed)],
    }
