import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const options=Object.fromEntries(process.argv.slice(2).reduce((a,v,i,all)=>i%2?a:[...a,[v.replace(/^--/,''),all[i+1]]],[]));
if(!options.output||!options['fixture-dir']||!options.browser)throw Error('output, fixture-dir and browser required');
await fs.mkdir(options.output,{recursive:false});
const fixture=JSON.parse(await fs.readFile(path.join(options['fixture-dir'],'responses.json'),'utf8'));
const provenance=JSON.parse(await fs.readFile(path.join(options['fixture-dir'],'fixture-manifest.json'),'utf8'));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
assert.equal(hash(await fs.readFile(path.join(options['fixture-dir'],'responses.json'))),provenance.sha256);
for(const [file,digest] of Object.entries(provenance.source_sha256))assert.equal(hash(await fs.readFile(file)),digest,'Fixture source changed: '+file);
await fs.writeFile(path.join(options.output,'fixture-manifest.json'),JSON.stringify(provenance,null,2));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,executablePath:options.browser});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.tracing.start({screenshots:true,snapshots:true});
const page=await context.newPage(),errors=[],requests=[],scenarios=[];
let fail=false,holdA=false,legacy=false,holdEvidence=false,failEvidence=false,pending=[];
page.on('pageerror',e=>errors.push(String(e)));
const base='/orders/1/evidence-runs/'+fixture.bundle_id;
const pathways=fixture.responses[base+'/pathways'].records;
const keyA=pathways.find(p=>p.name.endsWith(' A')).pathway_key;
await page.route('**/api/orders/**',async route=>{
 const request=route.request(),url=new URL(request.url());requests.push({method:request.method(),path:url.pathname});
 assert.equal(request.method(),'GET','Explorer browsing must not enqueue analysis/search');
 if(fail)return route.fulfill({status:503,json:{detail:'synthetic read failure'}});
 if(failEvidence&&url.pathname.endsWith('/evidence'))return route.fulfill({status:503,json:{detail:'synthetic evidence failure'}});
 if(legacy&&url.pathname==='/api/orders/1/evidence-runs')return route.fulfill({json:{records:[],status:'legacy_unbound'}});
 const params=new URLSearchParams();for(const key of ['pathway_key','feature_id','track','mode','n','axis','model_id','cursor'])if(url.searchParams.has(key))params.set(key,url.searchParams.get(key));
 const key=url.pathname.replace(/^\/api/,'')+(params.size?'?'+params:'');
 const payload=fixture.responses[key];assert.ok(payload,'No real API fixture for '+key);
 if(holdA&&params.get('pathway_key')===keyA){pending.push({route,payload});return;}
 if(holdEvidence&&url.pathname.endsWith('/evidence')&&params.get('feature_id')===fixture.evidence_feature_id){pending.push({route,payload});return;}
 await route.fulfill({json:payload});
});
async function done(name){scenarios.push(name);const line=JSON.stringify({scenario:name,status:'passed'});console.log(line);await fs.appendFile(path.join(options.output,'stdout.log'),line+'\n');await fs.writeFile(path.join(options.output,'progress.json'),JSON.stringify(scenarios));}
try {
 await page.goto(`${options.url||'http://127.0.0.1:5173'}/tests/explorer.browser.html`);
 await page.getByText('Fixture pathway A · Synthetic · 5 features').waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('.recharts-line-dots circle').length>0);
 assert.ok((await page.locator('.recharts-line-dots circle').count())>0);
 await done('actual shared chart: points, precursor identities, full inventory');
 await page.getByRole('button',{name:/Fixture pathway A/}).click();
 await page.getByText('조회 범위 선택 경로 전체 · 5 precursor · 페이지 5').waitFor();
 await done('pathway membership includes full population independent of display Top N');
 await page.getByRole('button',{name:'±2 범위 확대'}).click();
 await page.getByText('±2 밖의 점은 잘립니다.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'전체 범위 복원'}).click();
 const plot=page.locator('.recharts-wrapper').first(),box=await plot.boundingBox();
 await page.mouse.move(box.x+box.width*.5,box.y+box.height*.4);
 await page.waitForFunction(()=>document.querySelector('.recharts-tooltip-wrapper')?.getAttribute('style')?.includes('visibility: visible'));
 await page.screenshot({path:path.join(options.output,'explorer-desktop.png'),fullPage:true});
 await done('hover tooltip and explicit zoom/restoration');
 await page.getByLabel('Explorer track').selectOption('occupancy');
 await page.getByText('paired occupancy logit delta.',{exact:false}).waitFor();
 assert.equal(await page.locator('.recharts-line-dots circle').count(),0);
 await page.getByLabel('Explorer track').selectOption('unadjusted');
 await page.getByText('모델 입력과 다른 표현',{exact:false}).waitFor();
 await page.getByLabel('Explorer track').selectOption('relative');
 await done('track changes preserve unavailable occupancy and expose auxiliary U');
 await page.getByLabel('PTM display selection').selectOption('global_top_n');
 await page.getByLabel('Display N').fill('2');
 await page.getByText('조회 범위 선택 경로 전체 · 2 precursor · 페이지 2').waitFor();
 await page.getByLabel('PTM display selection').selectOption('per_condition_top_n');
 await page.getByLabel('PTM display selection').selectOption('inventory');
 await page.getByText('조회 범위 선택 경로 전체 · 5 precursor · 페이지 5').waitFor();
 await done('Top N and inventory modes change only read projection');
 const evidenceButton=page.locator(`[data-feature-id="${fixture.evidence_feature_id}"]`);
 await evidenceButton.click();
 await page.getByTestId('page-근거').getByText('근거: 전체 105건 · 현재 페이지 100건',{exact:false}).waitFor();
 await page.getByRole('button',{name:'근거 다음',exact:true}).click();
 await page.getByTestId('page-근거').getByText('근거: 전체 105건 · 현재 페이지 5건',{exact:false}).waitFor();
 await page.getByRole('button',{name:'보고서 주장 다음',exact:true}).click();
 await page.getByTestId('page-보고서 주장').getByText('보고서 주장: 전체 103건 · 현재 페이지 3건',{exact:false}).waitFor();
 assert.ok(!(await page.locator('body').innerText()).includes('PRIVATE'));
 await page.getByRole('button',{name:'근거 처음',exact:true}).click();
 const literature=page.locator('details').filter({has:page.locator('summary', {hasText:'literature_assertion'})}).first();
 await literature.locator('summary').click();
 assert.equal(await literature.getByRole('link',{name:'PMID 22222'}).getAttribute('href'),'https://pubmed.ncbi.nlm.nih.gov/22222/');
 await page.screenshot({path:path.join(options.output,'explorer-evidence.png'),fullPage:true});
 await done('sealed source spans, correct citation identity and complete paginated evidence/claim access');
 const otherId=fixture.responses[base+'/features'].records.find(f=>f.feature_id!==fixture.evidence_feature_id).feature_id;
 await page.locator(`[data-feature-id="${otherId}"]`).click();
 await page.getByTestId('page-근거').getByText('근거: 전체 1건 · 현재 페이지 1건',{exact:false}).waitFor();
 holdEvidence=true;await evidenceButton.click();
 await page.locator(`[data-feature-id="${otherId}"]`).click();
 await page.getByTestId('page-근거').getByText('근거: 전체 1건 · 현재 페이지 1건',{exact:false}).waitFor();
 holdEvidence=false;for(const p of pending.splice(0))await p.route.fulfill({json:p.payload}).catch(()=>{});
 await page.getByTestId('page-근거').getByText('근거: 전체 1건 · 현재 페이지 1건',{exact:false}).waitFor();
 await done('late evidence response and cursors cannot cross selected features');
 failEvidence=true;await evidenceButton.click();
 await page.getByRole('alert').filter({hasText:'근거 조회 실패:'}).waitFor();
 failEvidence=false;await page.getByRole('button',{name:'근거 다시 조회',exact:true}).click();
 await page.getByTestId('page-근거').getByText('근거: 전체 105건 · 현재 페이지 100건',{exact:false}).waitFor();
 await done('evidence-only failure remains visible and retries without hiding observations');
 await page.getByRole('button',{name:'partial_linear.v1 결과 보기',exact:true}).click();
 await page.getByTestId('comparison-results').getByText('모델 결과: 전체 5건 · 현재 페이지 5건',{exact:false}).waitFor();
 await page.getByRole('button',{name:'ksea_z.v1 결과 보기',exact:true}).click();
 await page.getByTestId('comparison-results').getByText('모델 결과: 전체 4건 · 현재 페이지 4건',{exact:false}).waitFor();
 await done('versioned comparison results are browsable without recomputing primary scores');
 await page.getByRole('button',{name:'전체 feature',exact:true}).click();
 holdA=true;await page.getByRole('button',{name:/Fixture pathway A/}).click();
 await page.getByRole('button',{name:/Fixture pathway B/}).click();
 await page.getByText('조회 범위 선택 경로 전체 · 1 precursor · 페이지 1').waitFor();
 holdA=false;for(const p of pending.splice(0))await p.route.fulfill({json:p.payload}).catch(()=>{});
 await page.getByText('조회 범위 선택 경로 전체 · 1 precursor · 페이지 1').waitFor();
 await done('late pathway A response cannot replace pathway B');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(options.output,'explorer-mobile.png'),fullPage:true});
 await done('390px mobile layout without document overflow');
 await page.getByLabel('분석 run').selectOption(fixture.parent_bundle_id);
 await page.getByText('보고서: not_requested · 문헌: not_requested').waitFor();
 await page.getByLabel('분석 run').selectOption(fixture.bundle_id);
 await page.getByText('보고서: completed · 문헌: available').waitFor();
 await done('parent analysis and report descendant keep separate immutable component bindings');
 legacy=true;await page.reload();
 await page.getByLabel('Legacy axis').waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('.recharts-line-dots circle').length>0);
 await page.getByLabel('Legacy axis').selectOption('unadjusted');
 await page.getByText('U: unadjusted log2 contrast (모델 입력과 다른 표현)',{exact:false}).waitFor();
 assert.equal(await page.getByText('A: protein-adjusted log2 contrast',{exact:false}).count(),0);
 await page.waitForFunction(()=>document.querySelectorAll('.recharts-line-dots circle').length>0);
 await page.screenshot({path:path.join(options.output,'explorer-legacy-unadjusted.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await done('legacy TSV observations without bundle, correct U label, points and mobile layout');
 legacy=false;
 fail=true;await page.reload();await page.getByRole('alert').waitFor();fail=false;
 await page.getByRole('button',{name:'다시 시도',exact:true}).click();
 await page.getByRole('button',{name:/Fixture pathway A/}).waitFor();
 await done('source error and explicit retry');
 assert.deepEqual(errors,[]);
 await fs.writeFile(path.join(options.output,'result.json'),JSON.stringify({status:'passed',scenarios,errors,requests,
  fixture_bundle:fixture.bundle_id,scope:'synthetic actual API/worker responses, production component; not authenticated operational E2E'},null,2));
 await fs.writeFile(path.join(options.output,'exit-code.txt'),'0\n');
} catch(error) {
 await page.screenshot({path:path.join(options.output,'failure.png'),fullPage:true});
 await fs.writeFile(path.join(options.output,'stderr.log'),String(error.stack||error));
 await fs.writeFile(path.join(options.output,'exit-code.txt'),'1\n');
 await fs.writeFile(path.join(options.output,'result.json'),JSON.stringify({status:'failed',error:String(error.stack||error),scenarios,errors,requests},null,2));throw error;
} finally {await context.tracing.stop({path:path.join(options.output,'trace.zip')});await browser.close();}
